### ISSUE TITLE
Love this project

### ISSUE THREAD

**Issue by ghost** [AbhisekhNayek/MagicNumber#1]
hi @AbhisekhNayek i tested out this project. I'm actually looking to contribute to new projects. I'm learning css currently. So i would love to contibute to this project on the Documentaion, html and css side if you like. This would be a great start for me. Also looked onto your README it was amazing. 

Can i contribute...

Thank you

**Comment by AbhisekhNayek** [comment]
Yes 👍

**Comment by ghost** [comment]
Thank you I will complete the changes and request a pull 👍

**Comment by ghost** [comment]
I'm closing the issue
